name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo para clonar o repositório
      - uses: actions/checkout@v2

      # Passo para gerar a animação da cobrinha
      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: MrHitalo # Substitua pelo seu nome de usuário
          outputs: dist

      # Passo para fazer o deploy da animação para a branch "output"
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
